"""Build self-contained Kaggle kernels for the C1 Clean RealMLP run.

The generated ``kernel.py`` contains a compressed copy of the required
``mscapital`` modules, so it does not execute Python files from an attached
dataset.  ``--push`` is intentionally explicit and still requires an already
authenticated Kaggle CLI session.
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import subprocess
import zipfile
from pathlib import Path


OUTERS = ("PSEUDO", "H2", "T3", "T4")


def _package_payload(src_root: Path) -> str:
    names = (
        "__init__.py",
        "artifacts.py",
        "diagnostics.py",
        "metrics.py",
        "splits.py",
        "models/__init__.py",
        "models/realmlp.py",
    )
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in names:
            archive.writestr(f"mscapital/{name}", (src_root / name).read_bytes())
    return base64.b64encode(stream.getvalue()).decode("ascii")


def _kernel_code(payload: str, outer: str) -> str:
    return f'''# Generated by scripts/build_kaggle_c1.py; do not edit manually.
import base64, io, os, subprocess, sys, zipfile

_target_torch = "2.2.2"
try:
    import torch as _t0
    _cap = _t0.cuda.get_device_capability(0) if _t0.cuda.is_available() else (0, 0)
    _version = _t0.__version__.split("+", 1)[0]
except Exception:
    _cap, _version = (0, 0), "unknown"
if _cap[0] and _cap[0] < 7 and _version != _target_torch:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", f"torch=={{_target_torch}}", "numpy<2"])
    os.execv(sys.executable, [sys.executable] + sys.argv)

_payload = "{payload}"
_zip_path = "/kaggle/working/mscapital_payload.zip"
with open(_zip_path, "wb") as _handle:
    _handle.write(base64.b64decode(_payload))
sys.path.insert(0, _zip_path)

from mscapital.models.realmlp import RealMLPConfig, load_frame, run_outer

_cfg = RealMLPConfig(
    seed=2026, n_ens=16, embed_dim=6, learning_rate=1e-3, epochs=10,
    train_batch_size=256, eval_batch_size=2048, hidden_dim=24, dropout=0.01,
    ema_decay=0.998, gradient_clip=1.0, target_round=4, quantile_bins=40,
    correlation_threshold=0.90, low_target_correlation=0.0001,
    rq_layers=3, rq_vocab_size=3, lambda_cos=0.01, lambda_rq=0.1,
    label_noise_std=0.005, categorical_columns=("t_large_sell_95",), device="auto",
)
_train = "/kaggle/input/msc-f0726-pq/f0726_train_f32.parquet"
_labels = "/kaggle/input/competitions/ms-capital-real-financial-market-forecasting/train/label.feather"
_frame = load_frame(_train, _labels)
_result = run_outer(
    _frame, "{outer}", _cfg,
    "/kaggle/working/clean-realmlp-v2a",
    data_paths=(_train, _labels),
)
print({{"outer": "{outer}", "score": _result["diagnostics"]["cosine_uncentered"], "status": "complete"}}, flush=True)
'''


def build(repo: Path, output: Path, push: bool = False) -> None:
    payload = _package_payload(repo / "src" / "mscapital")
    output.mkdir(parents=True, exist_ok=True)
    for outer in OUTERS:
        slug = f"msc-clean-realmlp-v2a-{outer.lower()}"
        directory = output / outer.lower()
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "kernel.py").write_text(_kernel_code(payload, outer), encoding="utf-8")
        metadata = {
            "id": f"kasselmenike/{slug}",
            "title": f"MSCapital C1 Clean RealMLP-v2a {outer}",
            "code_file": "kernel.py",
            "language": "python",
            "kernel_type": "script",
            "is_gpu": True,
            "enable_internet": True,
            "dataset_sources": ["kasselmenike/msc-f0726-pq"],
            "competition_sources": ["ms-capital-real-financial-market-forecasting"],
            "enable_tpu": False,
        }
        (directory / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        if push:
            subprocess.run(["python", "-m", "kaggle", "kernels", "push", "-p", str(directory)], check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=Path("output/kaggle_c1_kernels"))
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()
    build(args.repo, args.output, args.push)


if __name__ == "__main__":
    main()
