"""Build self-contained Kaggle kernels and an optional private C3 data bundle."""

from __future__ import annotations

import argparse
import base64
import io
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path


OUTERS = ("PSEUDO", "H2", "T3", "T4")
DATASET_SLUG = "msc-clean-table-v2-data"


def _package_payload(src_root: Path) -> str:
    names = (
        "__init__.py", "artifacts.py", "diagnostics.py", "metrics.py", "splits.py",
        "models/__init__.py", "models/residual_catboost.py", "models/clean_table.py",
    )
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in names:
            archive.writestr(f"mscapital/{name}", (src_root / name).read_bytes())
    return base64.b64encode(stream.getvalue()).decode("ascii")


def _kernel_code(payload: str, outer: str, git_sha: str, config: dict, experiment_id: str) -> str:
    config_json = json.dumps(config, sort_keys=True, separators=(",", ":"))
    return f'''# Generated by scripts/build_kaggle_c3.py; do not edit manually.
import base64, glob, json, os, subprocess, sys

_target_torch = "2.2.2"
try:
    import torch as _t0
    _cap = _t0.cuda.get_device_capability(0) if _t0.cuda.is_available() else (0, 0)
    _version = _t0.__version__.split("+", 1)[0]
except Exception:
    _cap, _version = (0, 0), "unknown"
if _cap[0] and _cap[0] < 7 and _version != _target_torch:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", f"torch=={{_target_torch}}", "numpy<2"])
    os.execv(sys.executable, [sys.executable] + sys.argv)

_zip_path = "/kaggle/working/mscapital_payload.zip"
with open(_zip_path, "wb") as _handle:
    _handle.write(base64.b64decode("{payload}"))
sys.path.insert(0, _zip_path)
os.environ["MSCAP_GIT_SHA"] = "{git_sha}"

from mscapital.models.clean_table import CleanTableConfig, load_table_frame, run_outer

_cfg = CleanTableConfig.from_mapping(json.loads({config_json!r}))
_features = glob.glob("/kaggle/input/**/train_features.parquet", recursive=True)
_micro = glob.glob("/kaggle/input/**/micro_features_train.parquet", recursive=True)
_labels = glob.glob("/kaggle/input/**/label.feather", recursive=True)
print({{"features": _features, "micro": _micro, "labels": _labels}}, flush=True)
if len(_features) != 1 or len(_micro) != 1 or len(_labels) != 1:
    raise RuntimeError("Expected exactly one official feature, micro feature, and competition label file")
_frame = load_table_frame(_features[0], _micro[0], _labels[0])
_result = run_outer(
    _frame, "{outer}", _cfg, "/kaggle/working/{experiment_id}",
    experiment_id="{experiment_id}", data_paths=(_features[0], _micro[0], _labels[0]),
)
print({{"outer": "{outer}", "score": _result["score"], "status": "complete"}}, flush=True)
'''


def stage_dataset(data_root: Path, output: Path) -> Path:
    output.mkdir(parents=True, exist_ok=True)
    for name in ("train_features.parquet", "micro_features_train.parquet"):
        source = data_root / "processed" / name
        if not source.exists():
            raise FileNotFoundError(source)
        target = output / name
        if not target.exists() or target.stat().st_size != source.stat().st_size:
            shutil.copy2(source, target)
    metadata = {
        "title": "MSCapital Clean Table v2 Data",
        "id": f"kasselmenike/{DATASET_SLUG}",
        "licenses": [{"name": "other"}],
        "isPrivate": True,
    }
    (output / "dataset-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return output


def build_kernels(
    repo: Path, output: Path, *, config_path: Path, experiment_id: str,
    kernel_prefix: str, outers: tuple[str, ...], push: bool,
) -> None:
    payload = _package_payload(repo / "src" / "mscapital")
    config = json.loads(config_path.read_text(encoding="utf-8"))
    git_sha = subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True).strip()
    output.mkdir(parents=True, exist_ok=True)
    for outer in outers:
        slug = f"{kernel_prefix}-{outer.lower()}"
        directory = output / outer.lower()
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "kernel.py").write_text(
            _kernel_code(payload, outer, git_sha, config, experiment_id), encoding="utf-8"
        )
        metadata = {
            "id": f"kasselmenike/{slug}", "title": f"{kernel_prefix} {outer.lower()}",
            "code_file": "kernel.py", "language": "python", "kernel_type": "script",
            "enable_gpu": True, "enable_internet": True,
            "dataset_sources": [f"kasselmenike/{DATASET_SLUG}"],
            "competition_sources": ["ms-capital-real-financial-market-forecasting"],
            "enable_tpu": False,
        }
        (directory / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        if push:
            subprocess.run([sys.executable, "-m", "kaggle", "kernels", "push", "-p", str(directory)], check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=Path("output/kaggle_c3_kernels"))
    parser.add_argument("--config", type=Path)
    parser.add_argument("--experiment-id", default="clean-table-v2")
    parser.add_argument("--kernel-prefix", default="mscapital-c3-clean-table-v2")
    parser.add_argument("--outer", action="append", choices=OUTERS)
    parser.add_argument("--push", action="store_true")
    parser.add_argument("--stage-data", action="store_true")
    parser.add_argument("--data-root", type=Path)
    parser.add_argument("--dataset-output", type=Path, default=Path("output/kaggle_c3_dataset"))
    parser.add_argument("--create-dataset", action="store_true")
    args = parser.parse_args()
    if args.stage_data or args.create_dataset:
        if args.data_root is None:
            parser.error("--data-root is required when staging or creating the dataset")
        dataset_dir = stage_dataset(args.data_root, args.dataset_output)
        if args.create_dataset:
            subprocess.run([sys.executable, "-m", "kaggle", "datasets", "create", "-p", str(dataset_dir)], check=True)
    config_path = args.config or args.repo / "configs" / "clean-table-v2.json"
    build_kernels(
        args.repo, args.output, config_path=config_path, experiment_id=args.experiment_id,
        kernel_prefix=args.kernel_prefix, outers=tuple(args.outer or OUTERS), push=args.push,
    )


if __name__ == "__main__":
    main()
