"""Build self-contained Kaggle kernels for the C1 Clean RealMLP run.

The generated ``kernel.py`` contains a compressed copy of the required
``mscapital`` modules, so it does not execute Python files from an attached
dataset.  ``--push`` is intentionally explicit and still requires an already
authenticated Kaggle CLI session.
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import subprocess
import sys
import zipfile
from pathlib import Path


OUTERS = ("PSEUDO", "H2", "T3", "T4")


def _package_payload(src_root: Path) -> str:
    names = (
        "__init__.py",
        "artifacts.py",
        "diagnostics.py",
        "metrics.py",
        "splits.py",
        "models/__init__.py",
        "models/residual_catboost.py",
        "models/realmlp.py",
    )
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in names:
            archive.writestr(f"mscapital/{name}", (src_root / name).read_bytes())
    return base64.b64encode(stream.getvalue()).decode("ascii")


def _kernel_code(payload: str, outer: str, git_sha: str, config: dict, experiment_id: str, mode: str) -> str:
    config_json = json.dumps(config, sort_keys=True, separators=(",", ":"))
    return f'''# Generated by scripts/build_kaggle_c1.py; do not edit manually.
import base64, glob, io, json, os, subprocess, sys, zipfile

_target_torch = "2.2.2"
try:
    import torch as _t0
    _cap = _t0.cuda.get_device_capability(0) if _t0.cuda.is_available() else (0, 0)
    _version = _t0.__version__.split("+", 1)[0]
except Exception:
    _cap, _version = (0, 0), "unknown"
if _cap[0] and _cap[0] < 7 and _version != _target_torch:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", f"torch=={{_target_torch}}", "numpy<2"])
    os.execv(sys.executable, [sys.executable] + sys.argv)

_payload = "{payload}"
_zip_path = "/kaggle/working/mscapital_payload.zip"
with open(_zip_path, "wb") as _handle:
    _handle.write(base64.b64decode(_payload))
sys.path.insert(0, _zip_path)
os.environ["MSCAP_GIT_SHA"] = "{git_sha}"

from mscapital.models.realmlp import RealMLPConfig, load_frame, run_inner_diagnostic, run_outer

_cfg = RealMLPConfig.from_mapping(json.loads({config_json!r}))
_train_matches = glob.glob("/kaggle/input/**/f0726_train_f32.parquet", recursive=True)
_label_matches = glob.glob("/kaggle/input/**/label.feather", recursive=True)
print({{"train_matches": _train_matches, "label_matches": _label_matches}}, flush=True)
if len(_train_matches) != 1 or len(_label_matches) != 1:
    raise RuntimeError("Expected exactly one feature parquet and one competition label file")
_train = _train_matches[0]
_labels = _label_matches[0]
_frame = load_frame(_train, _labels)
_runner = run_inner_diagnostic if {mode!r} == "inner" else run_outer
_result = _runner(
    _frame, "{outer}", _cfg,
    "/kaggle/working/{experiment_id}",
    experiment_id="{experiment_id}",
    data_paths=(_train, _labels),
)
_score = _result["score"] if {mode!r} == "inner" else _result["diagnostics"]["cosine_uncentered"]
print({{"outer": "{outer}", "score": _score, "mode": {mode!r}, "status": "complete"}}, flush=True)
'''


def build(
    repo: Path,
    output: Path,
    *,
    config_path: Path,
    experiment_id: str,
    kernel_prefix: str,
    mode: str = "outer",
    outers: tuple[str, ...] = OUTERS,
    push: bool = False,
) -> None:
    payload = _package_payload(repo / "src" / "mscapital")
    config = json.loads(config_path.read_text(encoding="utf-8"))
    git_sha = subprocess.check_output(
        ["git", "-C", str(repo), "rev-parse", "HEAD"], text=True
    ).strip()
    output.mkdir(parents=True, exist_ok=True)
    for outer in outers:
        slug = f"{kernel_prefix}-{outer.lower()}"
        directory = output / outer.lower()
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "kernel.py").write_text(
            _kernel_code(payload, outer, git_sha, config, experiment_id, mode), encoding="utf-8"
        )
        metadata = {
            "id": f"kasselmenike/{slug}",
            "title": f"MSCapital {experiment_id} {outer}",
            "code_file": "kernel.py",
            "language": "python",
            "kernel_type": "script",
            "enable_gpu": True,
            "enable_internet": True,
            "dataset_sources": ["kasselmenike/msc-f0726-pq"],
            "competition_sources": ["ms-capital-real-financial-market-forecasting"],
            "enable_tpu": False,
        }
        (directory / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        if push:
            subprocess.run([sys.executable, "-m", "kaggle", "kernels", "push", "-p", str(directory)], check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, default=Path("output/kaggle_c1_kernels"))
    parser.add_argument("--config", type=Path)
    parser.add_argument("--experiment-id", default="clean-realmlp-v2a")
    parser.add_argument("--kernel-prefix", default="mscapital-c1-clean-realmlp-v2a")
    parser.add_argument("--mode", choices=("outer", "inner"), default="outer")
    parser.add_argument("--outer", action="append", choices=OUTERS)
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()
    config_path = args.config or args.repo / "configs" / "clean-realmlp-v2a.json"
    build(
        args.repo,
        args.output,
        config_path=config_path,
        experiment_id=args.experiment_id,
        kernel_prefix=args.kernel_prefix,
        mode=args.mode,
        outers=tuple(args.outer or OUTERS),
        push=args.push,
    )


if __name__ == "__main__":
    main()
